---
title: "Replication of Figure–Ground Illusion Study by Oishi et al. (2021, Psychological Science)"
author: "Peggy Yin (peggyyin@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction
Oishi et al. (2021) proposed that psychological richness—a life filled with variety, interesting experiences, and perspective change (both positive and negative)—is a distinct component of a good life, separate from happiness and meaning. The work directly connects to my research interest in the psychology of self-concept redefinition. I chose the figure–ground illusion study because it demonstrates that psychological richness can result from individuals recognizing multiple interpretations of a simple images in a short amount of time. Because my broader interests concern aesthetic reframing, and this experiment captures that process at a basic perceptual level. By showing that ambiguous visual stimuli can evoke a sense of richness without altering happiness or meaning, the study provides a minimal yet powerful model of how reinterpretation can contribute to well-being. 

The stimuli will be four figure-ground illusions where two-thirds of the participants see a figure-ground illusion (where both the foreground and background can be focused on, and a different image is produced depending on the focus), and the other one-third see altered images where the background image is disrupted, so that only the foreground focus will produce an image. The procedure will require participants to view and describe each of the four drawings, then self-report their moods and aesthetic evaluations of the image. One-third of the participants viewing the figure-ground images will be further prompted with the question “What else do you see?" Psychological richness will then be measured based on the mean of 11 items from the Psychological Richess Questionnaire (interesting, boring[r], intriguing, psychologically rich, complex, fresh, unique, surprised, unusual, typical[r], simple[r]) on a 1–5 point scale. Positive affect will be measured as the mean of 6 items from the SPANE (Diener et al., 2010): positive, good, pleasant, happy, joyful, content, on a 1–5 point scale. The challenges will be making sure I am replicating the study correctly, because the original study was split into two parts where participants were split in half, whereas my replication combines the two studies into one study where participants are divided in thirds. Moreover, I will need to email the authors for 3/4 of the stimuli used.

Replication Repository: [GitHub](https://github.com/peggyyyin/oishi2021)

Original Paper: [Paper](https://github.com/peggyyyin/oishi2021/tree/main/original_paper)

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
